// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.13.1_@biomejs+biome@1.8.3_@parcel+watcher@2.4.1_@types+node@22.5.4_ioredis@5.4.1_magic_2qh32ke6w6ddjh3wveup27dtjm/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@1.5.1_magicast@0.3.5_rollup@4.21.3_vite@5.4.4_@types+node@22.5.4_terser@5.32.0__vue@3.5.4_typescript@5.6.2_/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}